export const REMOVE_ARTICLE = 'REMOVE_ARTICLE'
export const ADD_ARTICLE = 'ADD_ARTICLE'

export const LOAD_ARTICLES_START = 'LOAD_ARTICLES_START'
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS'
export const LOAD_ARTICLES_FAIL = 'LOAD_ARTICLES_FAIL'