export const REMOVE_ARTICLE = 'REMOVE_ARTICLE'
export const ADD_ARTICLE = 'ADD_ARTICLE'

export const LOAD_ARTICLES = 'LOAD_ARTICLES'
export const LOAD_ARTICLES_START = 'LOAD_ARTICLES_START'
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS'
export const LOAD_ARTICLES_FAIL = 'LOAD_ARTICLES_FAIL'

export const LOAD_ARTICLE = 'LOAD_ARTICLE'
export const LOAD_ARTICLE_START = 'LOAD_ARTICLE_START'
export const LOAD_ARTICLE_SUCCESS = 'LOAD_ARTICLE_SUCCESS'
export const LOAD_ARTICLE_FAIL = 'LOAD_ARTICLE_FAIL'
